export const chatData = {
  conversations: [
    {
      id: 1,
      contact: {
        id: 2,
        name: "Alex",
        avatar: "/placeholder.svg?height=40&width=40",
        online: true,
      },
      messages: [
        {
          id: 1,
          senderId: 2,
          text: "Hi Sarah! I saw you have this denim jacket. Is it still available?",
          time: "10:30 AM",
        },
        {
          id: 2,
          senderId: 2,
          product: {
            id: 101,
            name: "Vintage Denim Jacket",
            price: 45.99,
            image: "/placeholder.svg?height=120&width=120",
            forSale: true,
            forTrade: false,
          },
          time: "10:31 AM",
        },
        {
          id: 3,
          senderId: 1,
          text: "Hey Alex! Yes, it's still available. Are you interested in buying it?",
          time: "10:33 AM",
        },
        {
          id: 4,
          senderId: 2,
          text: "Actually, I was wondering if you'd be interested in trading? I have this sweater that might be your style.",
          time: "10:35 AM",
        },
        {
          id: 5,
          senderId: 2,
          product: {
            id: 102,
            name: "Cashmere Sweater",
            price: 39.99,
            image: "/placeholder.svg?height=120&width=120",
            forSale: false,
            forTrade: true,
          },
          time: "10:36 AM",
        },
        {
          id: 6,
          senderId: 1,
          text: "That's a beautiful sweater! I might be interested. Let me think about it and get back to you.",
          time: "10:40 AM",
        },
        {
          id: 7,
          senderId: 2,
          text: "Sure, no rush! By the way, do you have any other vintage items?",
          time: "10:42 AM",
        },
        {
          id: 8,
          senderId: 1,
          text: "Yes, I just listed this dress yesterday. It's for sale only though.",
          time: "10:45 AM",
        },
        {
          id: 9,
          senderId: 1,
          product: {
            id: 103,
            name: "Floral Vintage Dress",
            price: 55.0,
            image: "/placeholder.svg?height=120&width=120",
            forSale: true,
            forTrade: false,
          },
          time: "10:46 AM",
        },
        {
          id: 10,
          senderId: 2,
          text: "That's gorgeous! I might just buy it outright. Let me check my size...",
          time: "10:48 AM",
        },
      ],
      lastMessage:
        "That's gorgeous! I might just buy it outright. Let me check my size...",
      time: "10:48 AM",
      unread: 0,
    },
    {
      id: 2,
      contact: {
        id: 3,
        name: "Maya",
        avatar: "/placeholder.svg?height=40&width=40",
        online: false,
      },
      messages: [
        {
          id: 1,
          senderId: 3,
          text: "Hello! I'm interested in the green dress you posted yesterday.",
          time: "Yesterday",
        },
        {
          id: 2,
          senderId: 3,
          product: {
            id: 201,
            name: "Emerald Green Dress",
            price: 65.0,
            image: "/placeholder.svg?height=120&width=120",
            forSale: true,
            forTrade: false,
          },
          time: "Yesterday",
        },
        {
          id: 3,
          senderId: 1,
          text: "Hi Maya! Yes, it's still available. It's in excellent condition, only worn once.",
          time: "Yesterday",
        },
        {
          id: 4,
          senderId: 3,
          text: "Great! What's the size? And do you ship internationally?",
          time: "Yesterday",
        },
        {
          id: 5,
          senderId: 1,
          text: "It's a size M (US 8-10). And yes, I do ship internationally, but shipping costs will vary depending on location.",
          time: "Yesterday",
        },
        {
          id: 6,
          senderId: 3,
          text: "Perfect! I'm in Canada. Is this still available?",
          time: "Yesterday",
        },
      ],
      lastMessage: "Is this still available?",
      time: "Yesterday",
      unread: 2,
    },
    {
      id: 3,
      contact: {
        id: 4,
        name: "Liam",
        avatar: "/placeholder.svg?height=40&width=40",
        online: true,
      },
      messages: [
        {
          id: 1,
          senderId: 4,
          text: "Hey Sarah, I noticed you're selling some vintage items. I have a leather jacket that I'd like to trade.",
          time: "Yesterday",
        },
        {
          id: 2,
          senderId: 1,
          text: "Hi Liam! I'm definitely open to trades. Could you send me some photos of the jacket?",
          time: "Yesterday",
        },
        {
          id: 3,
          senderId: 4,
          text: "Sure thing! Here's my vintage leather jacket. It's from the 90s, great condition.",
          time: "Yesterday",
        },
        {
          id: 4,
          senderId: 4,
          product: {
            id: 301,
            name: "Vintage Leather Jacket",
            price: 120.0,
            image: "/placeholder.svg?height=120&width=120",
            forSale: false,
            forTrade: true,
          },
          time: "Yesterday",
        },
        {
          id: 5,
          senderId: 1,
          text: "That's a beautiful jacket! What kind of items are you looking to trade for?",
          time: "Yesterday",
        },
        {
          id: 6,
          senderId: 4,
          text: "I'd like to trade my jacket for your vintage boots and maybe that denim skirt you posted last week.",
          time: "Yesterday",
        },
      ],
      lastMessage:
        "I'd like to trade my jacket for your vintage boots and maybe that denim skirt you posted last week.",
      time: "Yesterday",
      unread: 0,
    },
    {
      id: 4,
      contact: {
        id: 5,
        name: "Emma",
        avatar: "/placeholder.svg?height=40&width=40",
        online: false,
      },
      messages: [
        {
          id: 1,
          senderId: 5,
          text: "Hi Sarah! I just received the silk scarf today. It's even more beautiful in person!",
          time: "Monday",
        },
        {
          id: 2,
          senderId: 1,
          text: "I'm so glad you like it, Emma! It was one of my favorites, but I'm happy it found a good home.",
          time: "Monday",
        },
        {
          id: 3,
          senderId: 5,
          text: "The quality is amazing. Do you have any other accessories like this?",
          time: "Monday",
        },
        {
          id: 4,
          senderId: 1,
          text: "I actually just listed a vintage handbag that might interest you. Let me send you the details.",
          time: "Monday",
        },
        {
          id: 5,
          senderId: 1,
          product: {
            id: 401,
            name: "Vintage Leather Handbag",
            price: 85.0,
            image: "/placeholder.svg?height=120&width=120",
            forSale: true,
            forTrade: false,
          },
          time: "Monday",
        },
        {
          id: 6,
          senderId: 5,
          text: "Thanks for the quick response! That bag is gorgeous too.",
          time: "Monday",
        },
      ],
      lastMessage: "Thanks for the quick response! That bag is gorgeous too.",
      time: "Monday",
      unread: 0,
    },
    {
      id: 5,
      contact: {
        id: 6,
        name: "Noah",
        avatar: "/placeholder.svg?height=40&width=40",
        online: true,
      },
      messages: [
        {
          id: 1,
          senderId: 6,
          text: "Hello! I'm interested in the vintage camera you posted. Is it still working?",
          time: "Sunday",
        },
        {
          id: 2,
          senderId: 1,
          text: "Hi Noah! Yes, the camera is in working condition. I've tested it with film and everything functions properly.",
          time: "Sunday",
        },
        {
          id: 3,
          senderId: 6,
          text: "That's great to hear. And it comes with the original case, right?",
          time: "Sunday",
        },
        {
          id: 4,
          senderId: 1,
          text: "Yes, it includes the original leather case, strap, and even the manual.",
          time: "Sunday",
        },
        {
          id: 5,
          senderId: 6,
          text: "Perfect! Can you send more photos of it? I'd like to see the condition up close.",
          time: "Sunday",
        },
      ],
      lastMessage:
        "Can you send more photos of it? I'd like to see the condition up close.",
      time: "Sunday",
      unread: 1,
    },
  ],
};
